# Created by: David Kalliecharan <dave@dal.ca>
# $FreeBSD$

PORTNAME=	astor
PORTVERSION=	0.5
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	dave@dal.ca
COMMENT=	Astor allows easy manipulation of Python source via the AST

LICENSE=	BSD
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
