# Created by David Kalliecharan <dave@dal.ca>
# $FreeBSD$

PORTNAME=	astor
PORTVERSION=	0.5
PORTREVISION=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	dave@dal.ca
COMMENT=	astor allows easy manipulation of Python source via the AST

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python 
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
